#pragma once

#ifndef KTSERIAL_SIZE_TYPE
#define KTSERIAL_SIZE_TYPE uint64_t
#endif

#ifndef KTSERIAL_SERIALIZE_METHOD
#define KTSERIAL_SERIALIZE_METHOD serialize
#endif

#ifndef KTSERIAL_SAVE_METHOD
#define KTSERIAL_SAVE_METHOD save
#endif

#ifndef KTSERIAL_LOAD_METHOD
#define KTSERIAL_LOAD_METHOD load
#endif

#ifndef KTSERIAL_SERIALIZE_FUNCTION
#define KTSERIAL_SERIALIZE_FUNCTION serialize
#endif

#ifndef KTSERIAL_SAVE_FUNCTION
#define KTSERIAL_SAVE_FUNCTION save
#endif

#ifndef KTSERIAL_LOAD_FUNCTION
#define KTSERIAL_LOAD_FUNCTION load
#endif
